spring.application.name=backend

# spring.datasource.url=postgresql://localhost:5432/mydatabase
# spring.datasource.username=myuser
# spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Connexion à la base de données
# S'il y a une variable SPRING_DATASOURCE_URL, on l'utilise. Sinon, on utilise localhost.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secret}

# Mise à jour automatique du schéma de la DB (utile pour démarrer)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}